name: Sync Folder to Destination Repo

on:
  push:
    branches:
      - main
    paths:
      - 'festival-site/**'
      - 'lab-site/**' # Triggers ONLY when files in this folder change
      # - main # Triggers on ANY change pushed to main

jobs:
  sync-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v5 # Upgraded to resolve the Node deprecation

      - name: Push Folder to Destination Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ORG_ACCESS_TOKEN }}
        with:
          source-directory: '/'
          destination-github-username: 'Whaaat-Lab'
          destination-repository-name: 'festival.whaaat.io'
          target-branch: 'main' # Files land directly in the root of 'main'


      - name: Push Folder to Lab Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ORG_ACCESS_TOKEN }}
        with:
          source-directory: '/'
          destination-github-username: 'Whaaat-Lab'
          destination-repository-name: 'lab.whaaat.io'
          target-branch: 'main' # Files land directly in the root of 'main'
